### ISSUE TITLE
Swift example?

### ISSUE THREAD

**Issue by bootstraponline** [facebook/remodel#1]
Is there an example of using remodel with Swift?

**Comment by ColinCampbell** [comment]
Hey :) Currently Remodel only supports ObjC, but I could definitely see it being useful for Swift or perhaps other languages. We'd have to figure out how to handle the plugins, given we currently

- have plugins rendering ObjC into methods/functions
- have the plugins returning types in the form of ObjC names/idioms which then get rendered by the functions in `objc-renderer.ts`

We should be able add Swift support, but I'm not sure where it would rank in terms of priority. If you'd want to take a stab at it, that would be awesome :)
