### ISSUE TITLE
Allow algebraic matching blocks to be nil

### ISSUE THREAD

**Issue by toulouse** [facebook/remodel#18]
Currently, algebraic type matchers are implemented approximately like so:

```
switch (_subtype) {
  case _SomethingA:
    aMatchHandler();
  ...
```

This means that it's required to create and pass in empty blocks for every handler, because a match that tries to call nil as a function will cause a crash. It would be convenient for code that is aiming to only handle specific matches to not need the wordy implementation of empty blocks, and this could be achieved by `if (aMatchHandler) { aMatchHandler(); }`.

**Comment by Gricha** [comment]
Proposed solution in https://github.com/facebook/remodel/pull/21

**Comment by ColinCampbell** [comment]
No movement on this, closing it out
