### ISSUE TITLE
Generate objects from JSON

### ISSUE THREAD

**Issue by avnerbarr** [facebook/remodel#23]
I was wondering if there is an easy way to generate the model objects from a JSON response

Thanks

**Comment by ColinCampbell** [comment]
In terms of creating instances of objects in your application, or fetching JSON from an endpoint and using that to generate objects using Remodel?

**Comment by avnerbarr** [comment]
I mean if I want to parse a Json object into those model objects that were generated. 

Is there an automated way to create a json parser that will create and populate the objects.

**Comment by ColinCampbell** [comment]
@avnerbarr there's no built-in support for parsing JSON objects in Remodel objects, but it would be relatively straight-forward to write a plugin that would do that for you, depending on if you need to add support for nested object types. Could you provide a sample response?

**Comment by avnerbarr** [comment]
I have a very complex JSON with lots of nesting but in general it could be something like
```
[
  {
    "_id": "586bc0e867eb88690303b838",
    "index": 0,
    "guid": "1a69dde7-59f3-4daf-8f94-76e168f71a4d",
    "isActive": false,
    "balance": "$1,496.45",
    "picture": "http://placehold.it/32x32",
    "age": 25,
    "eyeColor": "green",
    "name": "Julia Ford",
    "gender": "female",
    "company": "COMVEYOR",
    "email": "juliaford@comveyor.com",
    "phone": "+1 (857) 580-2018",
    "address": "416 Oriental Boulevard, Skyland, Tennessee, 3208",
    "about": "Lorem aute fugiat sunt sint magna qui et laboris. Aute ut ad ipsum cupidatat culpa ea sit cillum. Laborum irure id proident pariatur non nulla Lorem anim enim id voluptate deserunt aute dolor. Lorem ullamco deserunt laboris aliqua pariatur ex id. Mollit labore ea nostrud exercitation est culpa anim ea enim. Nisi reprehenderit ad ullamco do aliqua ea culpa cillum consectetur eu id amet ad.\r\n",
    "registered": "2015-02-13T10:05:01 -02:00",
    "latitude": -65.19895,
    "longitude": -95.259513,
    "tags": [
      "duis",
      "reprehenderit",
      "deserunt",
      "fugiat",
      "quis",
      "aliquip",
      "elit"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Lorena Day"
      },
      {
        "id": 1,
        "name": "Vanessa Pratt"
      },
      {
        "id": 2,
        "name": "Bridget Willis"
      }
    ],
    "greeting": "Hello, Julia Ford! You have 3 unread messages.",
    "favoriteFruit": "banana"
  }
]
```

**Comment by andrewcuneo** [comment]
@avnerbarr, this is an ideal use case for a plugin.

If you check out the section in [this](https://code.facebook.com/posts/1154141864616569/building-and-managing-ios-model-objects-with-remodel/) document called "Customizing Remodel", you can find a rough example of building a plugin. 

Also, [this](https://github.com/facebook/remodel/blob/master/CUSTOMIZATIONS.md) document has more thorough information about the mechanics of setting one up.

**Comment by calimarkus** [comment]
Here's a basic JSON plugin, that let's you both
- create an object from a JSON dictionary and
- create a JSON dictionary from an object

https://gist.github.com/calimarkus/c4287bea1a7ae5a9e2ebcd53d93e5c12

**This is not tested in any way and thus not production ready.**
Take it as a starting point to write your own plugin.
