### ISSUE TITLE
Support of Alternative Encoding Format

### ISSUE THREAD

**Issue by aidmony** [facebook/remodel#71]
Hi,

I am trying to add support (a new custom plugin) for alternative encoding format such as flatbuffer. There is a difficulty of supporting these encoding format, because they do not have switch cases in the decoding / encoding process. I am currently thinking of two possible solutions: 1) creating additional classes for each subtype, and then encode/decode an _adtObject (this will be casted to different subtype classes) instead; 2) simply encode/decode every declared properties.

Please let me know which approach will you recommend. Thanks!

**Comment by calimarkus** [comment]
How would you implement it without remodel? Remodel shouldn't limit your decision here. You can write a plugin that works either way.
