### ISSUE TITLE
Cast to %ld and %lu instead of issuing %zd and %tu specifiers for NSInteger and NSUInteger variables

### ISSUE THREAD

**Issue by rsanchezsaez** [facebook/remodel#90]
Xcode 9.3 is not happy when you use `%zd` and `%tu` as a specifier for `NSInteger` and `NSUInteger` variables. They will generate warnings either when compiling on an iPhone 5c, or when compiling on an iPhone 5s+ (compile to *Generic iOS device* to test it):
> Enum values with underlying type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead

This sucks if you have a project treating warnings as errors.

I suggest changing the implementation to the recommended *Xcode fix-it solution&: explicitly cast to `(long)` or `(unsigned long)` and use the `%ld`/`%lu` specifiers.

**Comment by calimarkus** [comment]
Only [one test uses it](https://github.com/facebook/remodel/search?utf8=%E2%9C%93&q=%25zd&type=), right? Do you want to send a PR?

**Comment by rsanchezsaez** [comment]
Thanks!
